/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datasets */
        get: operations["datasets_api_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dataset */
        get: operations["dataset_api_datasets__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{slug}/charts/{chart_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chart */
        get: operations["chart_api_datasets__slug__charts__chart_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{slug}/revisions/{revision_key}/charts/{chart_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Revision Chart */
        get: operations["revision_chart_api_datasets__slug__revisions__revision_key__charts__chart_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{slug}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_datasets__slug__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Compatibility */
        get: operations["health_compatibility_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChartArtifactResponse */
        ChartArtifactResponse: {
            /** Inferencelevel */
            inferenceLevel?: string | null;
            /** Items */
            items?: {
                [key: string]: unknown;
            }[] | null;
            /** Method */
            method?: string | null;
            /** Modelformula */
            modelFormula?: string | null;
            /** Stats */
            stats?: {
                [key: string]: unknown;
            }[] | null;
        } & {
            [key: string]: unknown;
        };
        /** DatasetResponse */
        DatasetResponse: {
            /**
             * Analysisstatus
             * @default exploratory_only
             */
            analysisStatus: string;
            /** Availableartifacts */
            availableArtifacts?: string[] | null;
            /**
             * Availablecharts
             * @deprecated
             */
            availableCharts?: string[] | null;
            /** Currentrevision */
            currentRevision?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Featurecount
             * @default 0
             */
            featureCount: number;
            /**
             * Featurekind
             * @default taxonomy
             */
            featureKind: string;
            /**
             * Featurelabel
             * @default 物种
             */
            featureLabel: string;
            /** Groupcounts */
            groupCounts?: {
                [key: string]: number;
            };
            /** Id */
            id: number;
            /** Name */
            name: string;
            provenance?: components["schemas"]["ProvenanceResponse"];
            /** Publishedat */
            publishedAt?: unknown | null;
            /**
             * Samplecount
             * @default 0
             */
            sampleCount: number;
            /** Slug */
            slug: string;
            /**
             * Speciescount
             * @default 0
             */
            speciesCount: number;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Code */
            code?: string | null;
            /** Detail */
            detail: string;
            /** Requestid */
            requestId?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ProvenanceResponse */
        ProvenanceResponse: {
            /**
             * Abundancescale
             * @default unknown
             */
            abundanceScale: string;
            /** Computeversion */
            computeVersion?: string | null;
            /** Covariates */
            covariates?: string[];
            /** Generatedat */
            generatedAt?: unknown | null;
            /** Groupmapping */
            groupMapping?: {
                [key: string]: string;
            };
            /**
             * Missingvaluepolicy
             * @default error
             */
            missingValuePolicy: string;
            /**
             * Normalization
             * @default unknown
             */
            normalization: string;
            /** Parametershash */
            parametersHash?: string | null;
            /** Revision */
            revision?: string | null;
            /** Sourcefilesize */
            sourceFileSize?: number | null;
            /** Sourcesha256 */
            sourceSha256?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** SummaryResponse */
        SummaryResponse: {
            /**
             * Analysisstatus
             * @default exploratory_only
             */
            analysisStatus: string;
            /** Availableartifacts */
            availableArtifacts?: string[];
            /** Currentrevision */
            currentRevision?: string | null;
            /** Datasetname */
            datasetName: string;
            /** Datasetslug */
            datasetSlug: string;
            /**
             * Featurekind
             * @default taxonomy
             */
            featureKind: string;
            /**
             * Featurelabel
             * @default 物种
             */
            featureLabel: string;
            /** Groupcounts */
            groupCounts?: {
                [key: string]: number;
            };
            provenance?: components["schemas"]["ProvenanceResponse"];
            /**
             * Totalfeatures
             * @default 0
             */
            totalFeatures: number;
            /** Totalsamples */
            totalSamples: number;
            /**
             * Totalspecies
             * @default 0
             */
            totalSpecies: number;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    datasets_api_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetResponse"][];
                };
            };
        };
    };
    dataset_api_datasets__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chart_api_datasets__slug__charts__chart_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                chart_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartArtifactResponse"] | {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    revision_chart_api_datasets__slug__revisions__revision_key__charts__chart_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                revision_key: string;
                chart_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartArtifactResponse"] | {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    summary_api_datasets__slug__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_compatibility_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    live_api_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
