/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analysis-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analysis Runs */
        get: operations["analysis_runs_api_analysis_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis-runs/{run_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analysis Run */
        get: operations["analysis_run_api_analysis_runs__run_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis-runs/{run_key}/artifacts/{artifact_key}/features/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scoped Analysis Features */
        post: operations["scoped_analysis_features_api_analysis_runs__run_key__artifacts__artifact_key__features_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis-runs/{run_key}/artifacts/{artifact_key}/projection-audits/{projection_kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Projection Audit */
        post: operations["projection_audit_api_analysis_runs__run_key__artifacts__artifact_key__projection_audits__projection_kind__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis-runs/{run_key}/artifacts/{artifact_key}/projection-audits/{projection_kind}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Projection Audit Metadata */
        post: operations["projection_audit_metadata_api_analysis_runs__run_key__artifacts__artifact_key__projection_audits__projection_kind__metadata_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis-runs/{run_key}/artifacts/{artifact_key}/projection-audits/{projection_kind}/options/{field}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Projection Audit Options */
        post: operations["projection_audit_options_api_analysis_runs__run_key__artifacts__artifact_key__projection_audits__projection_kind__options__field__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis-runs/{run_key}/artifacts/{artifact_key}/projection-audits/{projection_kind}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Projection Audit Rows */
        post: operations["projection_audit_rows_api_analysis_runs__run_key__artifacts__artifact_key__projection_audits__projection_kind__rows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis-runs/{run_key}/artifacts/{artifact_key}/projections/abundance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abundance Projection */
        post: operations["abundance_projection_api_analysis_runs__run_key__artifacts__artifact_key__projections_abundance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis-runs/{run_key}/artifacts/{artifact_key}/projections/{projection_kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chart Projection */
        post: operations["chart_projection_api_analysis_runs__run_key__artifacts__artifact_key__projections__projection_kind__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis-runs/{run_key}/artifacts/{artifact_key}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Complete Results */
        get: operations["complete_results_api_analysis_runs__run_key__artifacts__artifact_key__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis-runs/{run_key}/artifacts/{artifact_key}/results/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Complete Results */
        get: operations["download_complete_results_api_analysis_runs__run_key__artifacts__artifact_key__results_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis-runs/{run_key}/artifacts/{artifact_key}/samples/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scoped Analysis Samples */
        post: operations["scoped_analysis_samples_api_analysis_runs__run_key__artifacts__artifact_key__samples_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis-runs/{run_key}/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analysis Samples */
        get: operations["analysis_samples_api_analysis_runs__run_key__samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis-runs/{run_key}/samples/{sample_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analysis Sample */
        get: operations["analysis_sample_api_analysis_runs__run_key__samples__sample_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datasets */
        get: operations["datasets_api_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dataset */
        get: operations["dataset_api_datasets__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{slug}/charts/{chart_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chart */
        get: operations["chart_api_datasets__slug__charts__chart_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{slug}/revisions/{revision_key}/charts/{chart_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Revision Chart */
        get: operations["revision_chart_api_datasets__slug__revisions__revision_key__charts__chart_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{slug}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_datasets__slug__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Compatibility */
        get: operations["health_compatibility_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mag/downloads/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download */
        get: operations["download_api_mag_downloads__kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mag/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Features */
        get: operations["features_api_mag_features_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mag/features/{mag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Distribution */
        get: operations["distribution_api_mag_features__mag_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mag/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Heatmap */
        get: operations["heatmap_api_mag_heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mag/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_mag_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mag/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quality */
        get: operations["quality_api_mag_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mag/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Samples */
        get: operations["samples_api_mag_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mag/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Taxonomy */
        get: operations["taxonomy_api_mag_taxonomy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AbundanceProjectionRequest */
        AbundanceProjectionRequest: {
            /**
             * Ranking
             * @default mean_abundance
             * @constant
             */
            ranking: "mean_abundance";
            scope?: components["schemas"]["AnalysisScope"];
            /**
             * Topn
             * @default 20
             */
            topN: number;
        };
        /** AbundanceProjectionResponse */
        AbundanceProjectionResponse: {
            /** Artifactkey */
            artifactKey: string;
            /** Datasetrevision */
            datasetRevision: string;
            /** Datasetslug */
            datasetSlug: string;
            /** Featurekind */
            featureKind: string;
            /** Featurelabel */
            featureLabel: string;
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /** Projection */
            projection: {
                [key: string]: unknown;
            };
            /** Projectionkey */
            projectionKey: string;
            /** Runkey */
            runKey: string;
            /** Scope */
            scope: {
                [key: string]: unknown;
            };
            /** Series */
            series?: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        /** AnalysisArtifactResponse */
        AnalysisArtifactResponse: {
            /**
             * Abundancescale
             * @default unknown
             */
            abundanceScale: string;
            /** Coveragefraction */
            coverageFraction: number;
            /** Datasetrevision */
            datasetRevision?: string | null;
            /** Datasetslug */
            datasetSlug?: string | null;
            /** Featurekind */
            featureKind?: string | null;
            /** Featurelabel */
            featureLabel?: string | null;
            /** Groupcounts */
            groupCounts?: {
                [key: string]: number;
            };
            /** Key */
            key: string;
            /**
             * Normalization
             * @default unknown
             */
            normalization: string;
            /** Samplecount */
            sampleCount: number;
            /** Schemaversion */
            schemaVersion: string;
            /** Type */
            type: string;
            /** Uri */
            uri: string;
        };
        /** AnalysisFeaturePageResponse */
        AnalysisFeaturePageResponse: {
            /** Artifactkey */
            artifactKey: string;
            /** Featurekind */
            featureKind: string;
            /** Featurelabel */
            featureLabel: string;
            /** Items */
            items?: components["schemas"]["AnalysisFeatureResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Query
             * @default
             */
            query: string;
            /** Runkey */
            runKey: string;
            /** Sourcefeaturecount */
            sourceFeatureCount: number;
            /** Total */
            total: number;
        };
        /** AnalysisFeatureResponse */
        AnalysisFeatureResponse: {
            /** Detectedsamplecount */
            detectedSampleCount: number;
            /** Featureid */
            featureId: string;
            /** Fullname */
            fullName: string;
            /** Meanabundance */
            meanAbundance: number;
            /** Prevalence */
            prevalence: number;
            /** Rank */
            rank: number;
            /** Shortname */
            shortName: string;
        };
        /** AnalysisRunResponse */
        AnalysisRunResponse: {
            /** Artifacts */
            artifacts?: components["schemas"]["AnalysisArtifactResponse"][];
            /** Completedat */
            completedAt?: string | null;
            /** Createdat */
            createdAt?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /** Groupcounts */
            groupCounts?: {
                [key: string]: number;
            };
            /** Id */
            id: number;
            /** Key */
            key: string;
            /** Manifestversion */
            manifestVersion: string;
            /** Name */
            name: string;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            /** Pipeline */
            pipeline?: {
                [key: string]: unknown;
            };
            /** Provenance */
            provenance?: {
                [key: string]: unknown;
            };
            /** Publishedat */
            publishedAt?: string | null;
            /** Referencedatabases */
            referenceDatabases?: {
                [key: string]: unknown;
            }[];
            /** Samplecount */
            sampleCount: number;
            /** Status */
            status: string;
        };
        /** AnalysisSampleDetailResponse */
        AnalysisSampleDetailResponse: {
            /** Artifacts */
            artifacts?: {
                [key: string]: unknown;
            }[];
            /**
             * Cohortkey
             * @default
             */
            cohortKey: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Phenotype */
            phenotype: string;
            /** Runkey */
            runKey: string;
            /** Samplecode */
            sampleCode: string;
            /**
             * Sourcestudy
             * @default
             */
            sourceStudy: string;
        };
        /** AnalysisSamplePageResponse */
        AnalysisSamplePageResponse: {
            /** Artifactkey */
            artifactKey?: string | null;
            /** Availablefields */
            availableFields?: string[];
            /** Groupcounts */
            groupCounts?: {
                [key: string]: number;
            };
            /** Items */
            items?: components["schemas"]["AnalysisSampleResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Runkey */
            runKey: string;
            /** Total */
            total: number;
        };
        /** AnalysisSampleResponse */
        AnalysisSampleResponse: {
            /**
             * Cohortkey
             * @default
             */
            cohortKey: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Phenotype */
            phenotype: string;
            /** Samplecode */
            sampleCode: string;
            /**
             * Sourcestudy
             * @default
             */
            sourceStudy: string;
        };
        /**
         * AnalysisScope
         * @description The exact sample population used to build one analytical projection.
         */
        AnalysisScope: {
            /** Groups */
            groups?: ("AD" | "NC")[];
            /**
             * Mode
             * @default cohort
             * @enum {string}
             */
            mode: "cohort" | "group" | "subset" | "sample";
            /** Samplecodes */
            sampleCodes?: string[];
        };
        /** ChartArtifactResponse */
        ChartArtifactResponse: {
            /** Inferencelevel */
            inferenceLevel?: string | null;
            /** Items */
            items?: {
                [key: string]: unknown;
            }[] | null;
            /** Method */
            method?: string | null;
            /** Modelformula */
            modelFormula?: string | null;
            /** Stats */
            stats?: {
                [key: string]: unknown;
            }[] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ChartProjectionRequest
         * @description Scope and display parameters for a server-computed chart projection.
         */
        ChartProjectionRequest: {
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            scope?: components["schemas"]["AnalysisScope"];
            selection?: components["schemas"]["FeatureSelection"] | null;
            /**
             * Topn
             * @default 20
             */
            topN: number;
        };
        /** ChartProjectionResponse */
        ChartProjectionResponse: {
            /** Artifactkey */
            artifactKey: string;
            /** Datasetrevision */
            datasetRevision: string;
            /** Datasetslug */
            datasetSlug: string;
            /** Featurekind */
            featureKind: string;
            /** Featurelabel */
            featureLabel: string;
            /** Payload */
            payload: unknown;
            /** Projection */
            projection: {
                [key: string]: unknown;
            };
            /** Projectionkey */
            projectionKey: string;
            /** Runkey */
            runKey: string;
            /** Scope */
            scope: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** CompleteResultPageResponse */
        CompleteResultPageResponse: {
            /** Artifactkey */
            artifactKey: string;
            /** Columns */
            columns?: string[];
            /** Datasetrevision */
            datasetRevision: string;
            /** Datasetslug */
            datasetSlug: string;
            /** Featurekind */
            featureKind: string;
            /** Featurelabel */
            featureLabel: string;
            /** Filters */
            filters?: {
                [key: string]: unknown;
            };
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Runkey */
            runKey: string;
            /** Sort */
            sort?: {
                [key: string]: string;
            };
            /** Storagesemantics */
            storageSemantics?: {
                [key: string]: unknown;
            };
            /** Total */
            total: number;
        } & {
            [key: string]: unknown;
        };
        /** DatasetResponse */
        DatasetResponse: {
            /**
             * Analysisstatus
             * @default exploratory_only
             */
            analysisStatus: string;
            /** Availableartifacts */
            availableArtifacts?: string[] | null;
            /**
             * Availablecharts
             * @deprecated
             */
            availableCharts?: string[] | null;
            /** Currentrevision */
            currentRevision?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Featurecount
             * @default 0
             */
            featureCount: number;
            /**
             * Featurekind
             * @default taxonomy
             */
            featureKind: string;
            /**
             * Featurelabel
             * @default 物种
             */
            featureLabel: string;
            /** Groupcounts */
            groupCounts?: {
                [key: string]: number;
            };
            /** Id */
            id: number;
            /** Name */
            name: string;
            provenance?: components["schemas"]["ProvenanceResponse"];
            /** Publishedat */
            publishedAt?: unknown | null;
            /**
             * Samplecount
             * @default 0
             */
            sampleCount: number;
            /** Slug */
            slug: string;
            /**
             * Speciescount
             * @default 0
             */
            speciesCount: number;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Code */
            code?: string | null;
            /** Detail */
            detail: string;
            /** Requestid */
            requestId?: string | null;
        };
        /**
         * FeatureSelection
         * @description A chart-independent feature selection that survives scope changes.
         */
        FeatureSelection: {
            /** Featureids */
            featureIds?: string[];
            /**
             * Limit
             * @default 30
             */
            limit: number;
            /**
             * Mode
             * @default ranked
             * @enum {string}
             */
            mode: "ranked" | "explicit";
            /**
             * Ranking
             * @default mean_abundance
             * @constant
             */
            ranking: "mean_abundance";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MagBox */
        MagBox: {
            /** Group */
            group: string;
            /** N */
            n: number;
            /** Values */
            values: number[];
        };
        /** MagDistributionResponse */
        MagDistributionResponse: {
            /** Boxes */
            boxes: components["schemas"]["MagBox"][];
            feature: components["schemas"]["MagFeature"];
            provenance: components["schemas"]["MagProvenance"];
            /** Samples */
            samples: components["schemas"]["MagDistributionSample"][];
        };
        /** MagDistributionSample */
        MagDistributionSample: {
            /** Abundancepercent */
            abundancePercent: number;
            /** Age */
            age: number;
            /** Batch */
            batch: string;
            /**
             * Disease
             * @enum {string}
             */
            disease: "AD" | "NC";
            /**
             * Gender
             * @enum {string}
             */
            gender: "F" | "M";
            /** Mappedpercent */
            mappedPercent: number;
            /** Sampleid */
            sampleId: string;
            /** Unmappedpercent */
            unmappedPercent: number;
        };
        /** MagErrorResponse */
        MagErrorResponse: {
            /** Detail */
            detail: string;
            /** Report */
            report?: {
                [key: string]: string;
            } | null;
        };
        /** MagFeature */
        MagFeature: {
            /** Adabovethresholdpercent */
            adAboveThresholdPercent: number | null;
            /** Admeanpercent */
            adMeanPercent: number | null;
            /** Admedianpercent */
            adMedianPercent: number | null;
            /** Lengthbp */
            lengthBp: number;
            /** Magid */
            magId: string;
            /** Meandifferencepercentpoints */
            meanDifferencePercentPoints: number | null;
            /** Meanpercent */
            meanPercent: number | null;
            /** Ncabovethresholdpercent */
            ncAboveThresholdPercent: number | null;
            /** Ncmeanpercent */
            ncMeanPercent: number | null;
            /** Ncmedianpercent */
            ncMedianPercent: number | null;
            /** Pvalue */
            pValue: number | null;
            /** Qvalue */
            qValue: number | null;
            /** Rankbiserial */
            rankBiserial: number | null;
        };
        /** MagFeaturePageResponse */
        MagFeaturePageResponse: {
            /** Direction */
            direction: string;
            /** Items */
            items: components["schemas"]["MagFeature"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            provenance: components["schemas"]["MagProvenance"];
            /** Query */
            query: string;
            /** Sortby */
            sortBy: string;
            /** Total */
            total: number;
        };
        /** MagHeatmapResponse */
        MagHeatmapResponse: {
            /** Magids */
            magIds: string[];
            provenance: components["schemas"]["MagProvenance"];
            /** Samples */
            samples: components["schemas"]["MagSample"][];
            /** Selection */
            selection: string;
            /** Values */
            values: number[][];
        };
        /** MagOverviewResponse */
        MagOverviewResponse: {
            /** Batches */
            batches: {
                [key: string]: string | number;
            }[];
            /** Capabilities */
            capabilities: {
                [key: string]: boolean;
            };
            /** Options */
            options: {
                [key: string]: unknown;
            };
            provenance: components["schemas"]["MagProvenance"];
        };
        /** MagProvenance */
        MagProvenance: {
            /** Analysisversion */
            analysisVersion: string;
            /** Datafingerprint */
            dataFingerprint: string;
            /** Excludedsamplecount */
            excludedSampleCount: number;
            filters: components["schemas"]["MagScopeResponse"];
            /** Groupcounts */
            groupCounts: {
                [key: string]: number;
            };
            /**
             * Groupfield
             * @constant
             */
            groupField: "disease";
            /** Magcount */
            magCount: number;
            /** Mappingtolerancepercentpoints */
            mappingTolerancePercentPoints: number;
            /** Maxmappingerrorpercentpoints */
            maxMappingErrorPercentPoints: number;
            /**
             * Provenancescope
             * @constant
             */
            provenanceScope: "runtime-input-and-downstream-analysis";
            /** Requestfingerprint */
            requestFingerprint: string;
            /** Samplecount */
            sampleCount: number;
            /** Sampleids */
            sampleIds: string[];
            /** Sources */
            sources: components["schemas"]["MagSource"][];
            /** Testedfeaturecount */
            testedFeatureCount: number;
            /**
             * Unit
             * @constant
             */
            unit: "%";
            upstreamGeneration: components["schemas"]["MagUpstreamGeneration"] | null;
            /** Version */
            version: string;
            /** Warnings */
            warnings: string[];
        };
        /** MagQualityItem */
        MagQualityItem: {
            /** Codingdensity */
            codingDensity: number;
            /** Completenessmodel */
            completenessModel: string;
            /** Completenesspercent */
            completenessPercent: number;
            /** Contaminationpercent */
            contaminationPercent: number;
            /** Contign50Bp */
            contigN50Bp: number;
            /** Gccontent */
            gcContent: number;
            /** Genomesizebp */
            genomeSizeBp: number;
            /** Inreferenceband */
            inReferenceBand: boolean;
            /** Magid */
            magId: string;
            /** Maxcontiglengthbp */
            maxContigLengthBp: number;
            /** Totalcodingsequences */
            totalCodingSequences: number;
            /** Totalcontigs */
            totalContigs: number;
        };
        /** MagQualityReferenceBand */
        MagQualityReferenceBand: {
            /** Label */
            label: string;
            /** Maximumcontaminationpercent */
            maximumContaminationPercent: number;
            /** Minimumcompletenesspercent */
            minimumCompletenessPercent: number;
        };
        /** MagQualityResponse */
        MagQualityResponse: {
            /** Items */
            items: components["schemas"]["MagQualityItem"][];
            /** Method */
            method: string;
            provenance: components["schemas"]["MagProvenance"];
            referenceBand: components["schemas"]["MagQualityReferenceBand"];
            summary: components["schemas"]["MagQualitySummary"];
            /** Version */
            version: string | null;
        };
        /** MagQualitySummary */
        MagQualitySummary: {
            /** Completenessmaxpercent */
            completenessMaxPercent: number;
            /** Completenessminpercent */
            completenessMinPercent: number;
            /** Contaminationmaxpercent */
            contaminationMaxPercent: number;
            /** Contaminationminpercent */
            contaminationMinPercent: number;
            /** Referencebandcount */
            referenceBandCount: number;
            /** Totalmagcount */
            totalMagCount: number;
        };
        /** MagSample */
        MagSample: {
            /** Age */
            age: number;
            /** Batch */
            batch: string;
            /**
             * Disease
             * @enum {string}
             */
            disease: "AD" | "NC";
            /**
             * Gender
             * @enum {string}
             */
            gender: "F" | "M";
            /** Mappedpercent */
            mappedPercent: number;
            /** Sampleid */
            sampleId: string;
            /** Unmappedpercent */
            unmappedPercent: number;
        };
        /** MagSamplesResponse */
        MagSamplesResponse: {
            /** Items */
            items: components["schemas"]["MagThresholdSample"][];
            provenance: components["schemas"]["MagProvenance"];
        };
        /** MagScopeResponse */
        MagScopeResponse: {
            /** Abundancethresholdpercent */
            abundanceThresholdPercent: number;
            /** Agemax */
            ageMax: number | null;
            /** Agemin */
            ageMin: number | null;
            /** Batch */
            batch: string;
            /** Disease */
            disease: string;
            /** Gender */
            gender: string;
        };
        /** MagSource */
        MagSource: {
            /** Bytes */
            bytes: number;
            /** File */
            file: string;
            /** Sha256 */
            sha256: string;
        };
        /** MagTaxonomyResponse */
        MagTaxonomyResponse: {
            /** Distincttaxoncount */
            distinctTaxonCount: number;
            /** Items */
            items: components["schemas"]["MagTaxonomySummaryItem"][];
            /** Method */
            method: string;
            provenance: components["schemas"]["MagProvenance"];
            /**
             * Rank
             * @enum {string}
             */
            rank: "domain" | "phylum" | "class" | "order" | "family" | "genus" | "species";
            /** Resolvedmagcount */
            resolvedMagCount: number;
            /** Topn */
            topN: number;
            /** Totalmagcount */
            totalMagCount: number;
            /** Unresolvedmagcount */
            unresolvedMagCount: number;
            /** Version */
            version: string | null;
            /** Versionnote */
            versionNote: string | null;
        };
        /** MagTaxonomySummaryItem */
        MagTaxonomySummaryItem: {
            /** Count */
            count: number;
            /** Label */
            label: string;
            /** Percent */
            percent: number;
        };
        /** MagThresholdSample */
        MagThresholdSample: {
            /** Abovethresholdmagcount */
            aboveThresholdMagCount: number;
            /** Age */
            age: number;
            /** Batch */
            batch: string;
            /**
             * Disease
             * @enum {string}
             */
            disease: "AD" | "NC";
            /**
             * Gender
             * @enum {string}
             */
            gender: "F" | "M";
            /** Mappedpercent */
            mappedPercent: number;
            /** Sampleid */
            sampleId: string;
            /** Unmappedpercent */
            unmappedPercent: number;
        };
        /** MagUpstreamGeneration */
        MagUpstreamGeneration: {
            /** Bamcaching */
            bamCaching: string;
            /** Basis */
            basis: string;
            /** Genomeinputmode */
            genomeInputMode: string;
            /** Mapper */
            mapper: string;
            /** Methods */
            methods: string[];
            /** Minimumcoveredfraction */
            minimumCoveredFraction: number;
            /** Outputformat */
            outputFormat: string;
            /** Tool */
            tool: string;
            /** Toolversion */
            toolVersion: string;
        };
        /** ProjectionAuditMetadataResponse */
        ProjectionAuditMetadataResponse: {
            /** Artifact */
            artifact?: {
                [key: string]: unknown;
            };
            /** Columns */
            columns?: {
                [key: string]: unknown;
            }[];
            /** Kind */
            kind: string;
            /** Projectionkey */
            projectionKey: string;
            /** Samplescope */
            sampleScope?: {
                [key: string]: unknown;
            };
            /** Section */
            section: string;
            /** Sections */
            sections?: {
                [key: string]: unknown;
            }[];
            /** Summary */
            summary?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** ProjectionAuditOptionsResponse */
        ProjectionAuditOptionsResponse: {
            /** Field */
            field: string;
            /**
             * Hasmore
             * @default false
             */
            hasMore: boolean;
            /**
             * Initialorder
             * @default search_results
             */
            initialOrder: string;
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /**
             * Limit
             * @default 200
             */
            limit: number;
            /**
             * Mode
             * @default search_results
             */
            mode: string;
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /** Projectionkey */
            projectionKey: string;
            /**
             * Query
             * @default
             */
            query: string;
            /** Section */
            section: string;
            /** Sourcefeaturecount */
            sourceFeatureCount?: number | null;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * ProjectionAuditRequest
         * @description Exact projection identity plus lazy detail-table pagination.
         */
        ProjectionAuditRequest: {
            /** Filters */
            filters?: {
                [key: string]: string;
            };
            /**
             * Limit
             * @default 100
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            /** Projectionkey */
            projectionKey: string;
            /**
             * Query
             * @default
             */
            query: string;
            /**
             * Ranking
             * @default mean_abundance
             * @constant
             */
            ranking: "mean_abundance";
            scope?: components["schemas"]["AnalysisScope"];
            /**
             * Section
             * @default
             */
            section: string;
            selection?: components["schemas"]["FeatureSelection"] | null;
            /**
             * Sortby
             * @default
             */
            sortBy: string;
            /**
             * Sortdirection
             * @default asc
             * @enum {string}
             */
            sortDirection: "asc" | "desc";
            /**
             * Topn
             * @default 20
             */
            topN: number;
        };
        /** ProjectionAuditResponse */
        ProjectionAuditResponse: {
            /** Columns */
            columns?: {
                [key: string]: unknown;
            }[];
            /** Filteroptions */
            filterOptions?: {
                [key: string]: {
                    [key: string]: unknown;
                }[];
            };
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /** Kind */
            kind: string;
            /**
             * Limit
             * @default 100
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /** Projectionkey */
            projectionKey: string;
            /** Samplescope */
            sampleScope?: {
                [key: string]: unknown;
            };
            /** Section */
            section: string;
            /** Sections */
            sections?: {
                [key: string]: unknown;
            }[];
            /** Summary */
            summary?: {
                [key: string]: unknown;
            };
            /**
             * Total
             * @default 0
             */
            total: number;
        } & {
            [key: string]: unknown;
        };
        /** ProjectionAuditRowsResponse */
        ProjectionAuditRowsResponse: {
            /** Columns */
            columns?: {
                [key: string]: unknown;
            }[];
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /** Kind */
            kind: string;
            /**
             * Limit
             * @default 100
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /** Projectionkey */
            projectionKey: string;
            /** Section */
            section: string;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** ProvenanceResponse */
        ProvenanceResponse: {
            /**
             * Abundancescale
             * @default unknown
             */
            abundanceScale: string;
            /** Computeversion */
            computeVersion?: string | null;
            /** Covariates */
            covariates?: string[];
            /** Generatedat */
            generatedAt?: unknown | null;
            /** Groupmapping */
            groupMapping?: {
                [key: string]: string;
            };
            /**
             * Missingvaluepolicy
             * @default error
             */
            missingValuePolicy: string;
            /**
             * Normalization
             * @default unknown
             */
            normalization: string;
            /** Parametershash */
            parametersHash?: string | null;
            /** Revision */
            revision?: string | null;
            /** Sourcefilesize */
            sourceFileSize?: number | null;
            /** Sourcesha256 */
            sourceSha256?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ScopedFeatureRequest
         * @description Search and rank the complete feature catalog within one sample scope.
         */
        ScopedFeatureRequest: {
            /** Featureids */
            featureIds?: string[];
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /**
             * Query
             * @default
             */
            query: string;
            scope?: components["schemas"]["AnalysisScope"];
        };
        /**
         * ScopedSampleRequest
         * @description Lightweight sample-metadata query bound to one analytical scope.
         */
        ScopedSampleRequest: {
            /**
             * Limit
             * @default 100
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /**
             * Query
             * @default
             */
            query: string;
            scope?: components["schemas"]["AnalysisScope"];
        };
        /** SummaryResponse */
        SummaryResponse: {
            /**
             * Analysisstatus
             * @default exploratory_only
             */
            analysisStatus: string;
            /** Availableartifacts */
            availableArtifacts?: string[];
            /** Currentrevision */
            currentRevision?: string | null;
            /** Datasetname */
            datasetName: string;
            /** Datasetslug */
            datasetSlug: string;
            /**
             * Featurekind
             * @default taxonomy
             */
            featureKind: string;
            /**
             * Featurelabel
             * @default 物种
             */
            featureLabel: string;
            /** Groupcounts */
            groupCounts?: {
                [key: string]: number;
            };
            provenance?: components["schemas"]["ProvenanceResponse"];
            /**
             * Totalfeatures
             * @default 0
             */
            totalFeatures: number;
            /** Totalsamples */
            totalSamples: number;
            /**
             * Totalspecies
             * @default 0
             */
            totalSpecies: number;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analysis_runs_api_analysis_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRunResponse"][];
                };
            };
        };
    };
    analysis_run_api_analysis_runs__run_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRunResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scoped_analysis_features_api_analysis_runs__run_key__artifacts__artifact_key__features_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
                artifact_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScopedFeatureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisFeaturePageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projection_audit_api_analysis_runs__run_key__artifacts__artifact_key__projection_audits__projection_kind__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
                artifact_key: string;
                projection_kind: "abundance" | "composition" | "ko_contribution" | "boxplot" | "heatmap" | "detection" | "differential_ko" | "taxonomy" | "taxonomy_sankey" | "pca" | "pcoa";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectionAuditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionAuditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projection_audit_metadata_api_analysis_runs__run_key__artifacts__artifact_key__projection_audits__projection_kind__metadata_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
                artifact_key: string;
                projection_kind: "abundance" | "composition" | "ko_contribution" | "boxplot" | "heatmap" | "detection" | "differential_ko" | "taxonomy" | "taxonomy_sankey" | "pca" | "pcoa";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectionAuditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionAuditMetadataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projection_audit_options_api_analysis_runs__run_key__artifacts__artifact_key__projection_audits__projection_kind__options__field__post: {
        parameters: {
            query?: {
                query?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                run_key: string;
                artifact_key: string;
                projection_kind: "abundance" | "composition" | "ko_contribution" | "boxplot" | "heatmap" | "detection" | "differential_ko" | "taxonomy" | "taxonomy_sankey" | "pca" | "pcoa";
                field: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectionAuditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionAuditOptionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projection_audit_rows_api_analysis_runs__run_key__artifacts__artifact_key__projection_audits__projection_kind__rows_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
                artifact_key: string;
                projection_kind: "abundance" | "composition" | "ko_contribution" | "boxplot" | "heatmap" | "detection" | "differential_ko" | "taxonomy" | "taxonomy_sankey" | "pca" | "pcoa";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectionAuditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionAuditRowsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abundance_projection_api_analysis_runs__run_key__artifacts__artifact_key__projections_abundance_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
                artifact_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AbundanceProjectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbundanceProjectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chart_projection_api_analysis_runs__run_key__artifacts__artifact_key__projections__projection_kind__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
                artifact_key: string;
                projection_kind: "composition" | "ko_contribution" | "boxplot" | "heatmap" | "detection" | "differential_ko" | "taxonomy" | "taxonomy_sankey" | "pca" | "pcoa";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChartProjectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartProjectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_results_api_analysis_runs__run_key__artifacts__artifact_key__results_get: {
        parameters: {
            query?: {
                query?: string;
                sampleCode?: string;
                phenotype?: string;
                featureId?: string;
                sortBy?: string;
                sortDirection?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                run_key: string;
                artifact_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteResultPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_complete_results_api_analysis_runs__run_key__artifacts__artifact_key__results_download_get: {
        parameters: {
            query?: {
                query?: string;
                sampleCode?: string;
                phenotype?: string;
                featureId?: string;
                sortBy?: string;
                sortDirection?: string;
            };
            header?: never;
            path: {
                run_key: string;
                artifact_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scoped_analysis_samples_api_analysis_runs__run_key__artifacts__artifact_key__samples_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
                artifact_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScopedSampleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSamplePageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analysis_samples_api_analysis_runs__run_key__samples_get: {
        parameters: {
            query?: {
                artifactKey?: string | null;
                phenotype?: string | null;
                query?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                run_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSamplePageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analysis_sample_api_analysis_runs__run_key__samples__sample_code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
                sample_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSampleDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    datasets_api_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetResponse"][];
                };
            };
        };
    };
    dataset_api_datasets__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chart_api_datasets__slug__charts__chart_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                chart_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartArtifactResponse"] | {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    revision_chart_api_datasets__slug__revisions__revision_key__charts__chart_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                revision_key: string;
                chart_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartArtifactResponse"] | {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    summary_api_datasets__slug__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_compatibility_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    live_api_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    download_api_mag_downloads__kind__get: {
        parameters: {
            query?: {
                query?: string;
                sortBy?: "magId" | "meanPercent" | "adMeanPercent" | "ncMeanPercent" | "meanDifferencePercentPoints" | "qValue" | "rankBiserial";
                direction?: "asc" | "desc";
                view?: "features" | "distribution" | "heatmap" | "taxonomy" | "quality" | "mapping";
                topN?: number;
                magId?: string;
                limit?: number;
                offset?: number;
                revision?: string;
                disease?: "" | "AD" | "NC";
                gender?: "" | "F" | "M";
                batch?: "" | "1" | "2" | "3" | "4" | "5";
                ageMin?: number | null;
                ageMax?: number | null;
                abundanceThresholdPercent?: number;
            };
            header?: never;
            path: {
                kind: "features" | "matrix" | "samples" | "taxonomy" | "quality" | "provenance";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/csv": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagErrorResponse"];
                };
            };
        };
    };
    features_api_mag_features_get: {
        parameters: {
            query?: {
                query?: string;
                sortBy?: "magId" | "meanPercent" | "adMeanPercent" | "ncMeanPercent" | "meanDifferencePercentPoints" | "qValue" | "rankBiserial";
                direction?: "asc" | "desc";
                limit?: number;
                offset?: number;
                revision?: string;
                disease?: "" | "AD" | "NC";
                gender?: "" | "F" | "M";
                batch?: "" | "1" | "2" | "3" | "4" | "5";
                ageMin?: number | null;
                ageMax?: number | null;
                abundanceThresholdPercent?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagFeaturePageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagErrorResponse"];
                };
            };
        };
    };
    distribution_api_mag_features__mag_id__get: {
        parameters: {
            query?: {
                revision?: string;
                disease?: "" | "AD" | "NC";
                gender?: "" | "F" | "M";
                batch?: "" | "1" | "2" | "3" | "4" | "5";
                ageMin?: number | null;
                ageMax?: number | null;
                abundanceThresholdPercent?: number;
            };
            header?: never;
            path: {
                mag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagDistributionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagErrorResponse"];
                };
            };
        };
    };
    heatmap_api_mag_heatmap_get: {
        parameters: {
            query?: {
                topN?: number;
                revision?: string;
                disease?: "" | "AD" | "NC";
                gender?: "" | "F" | "M";
                batch?: "" | "1" | "2" | "3" | "4" | "5";
                ageMin?: number | null;
                ageMax?: number | null;
                abundanceThresholdPercent?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagHeatmapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagErrorResponse"];
                };
            };
        };
    };
    overview_api_mag_overview_get: {
        parameters: {
            query?: {
                revision?: string;
                disease?: "" | "AD" | "NC";
                gender?: "" | "F" | "M";
                batch?: "" | "1" | "2" | "3" | "4" | "5";
                ageMin?: number | null;
                ageMax?: number | null;
                abundanceThresholdPercent?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagOverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagErrorResponse"];
                };
            };
        };
    };
    quality_api_mag_quality_get: {
        parameters: {
            query?: {
                revision?: string;
                disease?: "" | "AD" | "NC";
                gender?: "" | "F" | "M";
                batch?: "" | "1" | "2" | "3" | "4" | "5";
                ageMin?: number | null;
                ageMax?: number | null;
                abundanceThresholdPercent?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagQualityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagErrorResponse"];
                };
            };
        };
    };
    samples_api_mag_samples_get: {
        parameters: {
            query?: {
                revision?: string;
                disease?: "" | "AD" | "NC";
                gender?: "" | "F" | "M";
                batch?: "" | "1" | "2" | "3" | "4" | "5";
                ageMin?: number | null;
                ageMax?: number | null;
                abundanceThresholdPercent?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagSamplesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagErrorResponse"];
                };
            };
        };
    };
    taxonomy_api_mag_taxonomy_get: {
        parameters: {
            query?: {
                rank?: "domain" | "phylum" | "class" | "order" | "family" | "genus" | "species";
                topN?: number;
                revision?: string;
                disease?: "" | "AD" | "NC";
                gender?: "" | "F" | "M";
                batch?: "" | "1" | "2" | "3" | "4" | "5";
                ageMin?: number | null;
                ageMax?: number | null;
                abundanceThresholdPercent?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagTaxonomyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagErrorResponse"];
                };
            };
        };
    };
}
